### ISSUE TITLE
[BUG] build_feature_extractor

### ISSUE THREAD

**Issue by quark412** [jamesdolezal/slideflow#297] opened 2023-06-15 13:19 UTC
## Description

When running build_feature_extractor, I get an error that says: ModuleNotFoundError: No module named 'timm.models.layers.helpers'.

## To Reproduce
My code sample is:

`import slideflow
from slideflow.model import build_feature_extractor

exm = build_feature_extractor('ctranspath', tile_px=299)`

The stack trace is:

ModuleNotFoundError: No module named 'timm.models.layers.helpers'

ModuleNotFoundError                       Traceback (most recent call last)
File <command-3658305805294829>:4
      1 import slideflow
      2 from slideflow.model import build_feature_extractor
----> 4 exm = build_feature_extractor('ctranspath', tile_px=299)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory.py:101, in build_feature_extractor(name, **kwargs)
     99     return build_tensorflow_feature_extractor(name, **kwargs)
    100 elif is_torch_extractor(name):
--> 101     return build_torch_feature_extractor(name, **kwargs)
    102 else:
    103     raise errors.InvalidFeatureExtractor(f"Unrecognized feature extractor: {name}")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory_torch.py:12, in build_torch_feature_extractor(name, **kwargs)
     10 if is_torch_extractor(name):
     11     if name in _torch_extractors:
---> 12         return _torch_extractors[name](**kwargs)
     13     else:
     14         return _torch_extractors[name+'_imagenet'](**kwargs)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory_torch.py:22, in ctranspath(tile_px, **kwargs)
     20 @register_torch
     21 def ctranspath(tile_px, **kwargs):
---> 22     from .ctranspath import CTransPathFeatures
     23     return CTransPathFeatures(center_crop=(tile_px != 224), **kwargs)

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:172, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    167 thread_local._nest_level += 1
    169 try:
    170     # Import the desired module. If you’re seeing this while debugging a failed import,
    171     # look at preceding stack frames for relevant error information.
--> 172     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    174     is_root_import = thread_local._nest_level == 1
    175     # `level` represents the number of leading dots in a relative import statement.
    176     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:19
     16 from torchvision import transforms
     17 from huggingface_hub import hf_hub_download
---> 19 from timm.models.layers.helpers import to_2tuple
     20 from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
     21 from timm.models.helpers import build_model_with_cfg

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:172, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    167 thread_local._nest_level += 1
    169 try:
    170     # Import the desired module. If you’re seeing this while debugging a failed import,
    171     # look at preceding stack frames for relevant error information.
--> 172     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    174     is_root_import = thread_local._nest_level == 1
    175     # `level` represents the number of leading dots in a relative import statement.
    176     # If it's zero, then this is an absolute import.

ModuleNotFoundError: No module named 'timm.models.layers.helpers'

## Environment:

Slideflow Version (e.g., 1.0): 2.0.5
OS (e.g., Ubuntu): Ubuntu on Databricks
How you installed Slideflow (pip, source): pip
Python version: 3.9
CUDA/cuDNN version:
GPU models and configuration: T4

## Other info

I got the same error when installing slideflow from source.

**Comment by quark412** [comment] 2023-06-16 13:17
Yes, it is installed. It is version 0.9.2.

**Comment by jamesdolezal** [comment] 2023-06-16 13:34
Thanks - it looks like this is a `timm` version issue. I'm able to reproduce the error when installing with the latest version of timm. Try re-installing timm with version < 0.9:

`pip install "timm<0.9"`

I'll also work on a compatibility patch update for the latest version of `timm`. If it's not straightforward and looks like it might take some time, I'll pin the `timm` version to <0.9 in the next patch update.

**Comment by quark412** [comment] 2023-06-16 20:55
Yes, that resolves the issue, thanks!

**Comment by jamesdolezal** [comment] 2023-08-08 13:34
Fixed in `2.1.0`

**Closed by jamesdolezal** 2023-08-08 13:34 UTC
Labels: bug, fixed
