### ISSUE TITLE
Using ctranspath for extractor on build_feature_extractor gives error

### ISSUE THREAD

**Issue by maxxfarma** [jamesdolezal/slideflow#381] opened 2024-06-06 18:37 UTC
## Description
There is a type error when I try to utilize ctranspath as the extractor for build_feature_extractor

extractor=['ctranspath']
for ex in extractor:
  exm = build_feature_extractor(ex, tile_px=299)

TypeError: 'int' object is not subscriptable

## Expected behavior

This should extract features for a deep learning model.

On databricks
 - Slideflow Version (e.g., 1.0): 2.3.0
 - OS (e.g., Ubuntu): Windows 11
 - How you installed Slideflow (`pip`, source): PyPl

**Comment by Meijian** [comment] 2024-07-24 18:21
@jamesdolezal I see the same problem on my end. Could you please help? Here are the more detailed error message.

TypeError: 'int' object is not subscriptable
File <command-2206128926937266>, line 4
      1 from slideflow.model import build_feature_extractor
      3 extractor=['ctranspath']
----> 4 exm = build_feature_extractor('ctranspath', tile_px=299)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory.py:175, in build_feature_extractor(name, backend, **kwargs)
    173     return build_tensorflow_feature_extractor(name, **kwargs)
    174 elif is_torch_extractor(name):
--> 175     return build_torch_feature_extractor(name, **kwargs)
    176 else:
    177     raise errors.InvalidFeatureExtractor(f"Unrecognized feature extractor: {name}")
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory_torch.py:15, in build_torch_feature_extractor(name, **kwargs)
     13 if is_torch_extractor(name):
     14     if name in _torch_extractors:
---> 15         return _torch_extractors[name](**kwargs)
     16     else:
     17         return _torch_extractors[name+'_imagenet'](**kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory_torch.py:47, in ctranspath(tile_px, **kwargs)
     44 @register_torch
     45 def ctranspath(tile_px, **kwargs):
     46     from .ctranspath import CTransPathFeatures
---> 47     return CTransPathFeatures(center_crop=(tile_px != 224), **kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:600, in CTransPathFeatures.__init__(self, device, center_crop)
    598 from slideflow.model import torch_utils
    599 self.device = torch_utils.get_device(device)
--> 600 self.model = _build_ctranspath_model()
    601 self.model.head = torch.nn.Identity().to(self.device)
    603 checkpoint_path = hf_hub_download(
    604     repo_id='jamesdolezal/CTransPath',
    605     filename='ctranspath.pth'
    606 )
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:99, in _build_ctranspath_model()
     90 def _build_ctranspath_model():
     91     model_kwargs = dict(
     92         patch_size=4,
     93         window_size=7,
   (...)
     97         embed_layer=ConvStem
     98     )
---> 99     return _create_swin_transformer('swin_tiny_patch4_window7_224', pretrained=False, **model_kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:81, in _create_swin_transformer(variant, pretrained, **kwargs)
     72 def _create_swin_transformer(variant, pretrained=False, **kwargs):
     73     cfg = {
     74         'url': 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth',
     75         'num_classes': 1000, 'input_size': (3, 224, 224), 'pool_size': None,
   (...)
     79         **kwargs
     80     }
---> 81     return build_model_with_cfg(
     82         SwinTransformer, variant, pretrained,
     83         default_cfg=cfg,
     84         img_size=cfg['input_size'][-2:],
     85         num_classes=cfg['num_classes'],
     86         pretrained_filter_fn=checkpoint_filter_fn,
     87         **kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/timm/models/_builder.py:406, in build_model_with_cfg(model_cls, variant, pretrained, pretrained_cfg, pretrained_cfg_overlay, model_cfg, feature_cfg, pretrained_strict, pretrained_filter_fn, kwargs_filter, **kwargs)
    404 # Instantiate the model
    405 if model_cfg is None:
--> 406     model = model_cls(**kwargs)
    407 else:
    408     model = model_cls(cfg=model_cfg, **kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:463, in SwinTransformer.__init__(self, img_size, patch_size, in_chans, num_classes, embed_dim, depths, num_heads, window_size, mlp_ratio, qkv_bias, drop_rate, attn_drop_rate, drop_path_rate, norm_layer, ape, patch_norm, embed_layer, use_checkpoint, weight_init, **kwargs)
    461 layers = []
    462 for i_layer in range(self.num_layers):
--> 463     layers += [BasicLayer(
    464         dim=int(embed_dim * 2 ** i_layer),
    465         input_resolution=(self.patch_grid[0] // (2 ** i_layer), self.patch_grid[1] // (2 ** i_layer)),
    466         depth=depths[i_layer],
    467         num_heads=num_heads[i_layer],
    468         window_size=window_size,
    469         mlp_ratio=self.mlp_ratio,
    470         qkv_bias=qkv_bias,
    471         drop=drop_rate,
    472         attn_drop=attn_drop_rate,
    473         drop_path=dpr[sum(depths[:i_layer]):sum(depths[:i_layer + 1])],
    474         norm_layer=norm_layer,
    475         downsample=PatchMerging if (i_layer < self.num_layers - 1) else None,
    476         use_checkpoint=use_checkpoint)
    477     ]
    478 self.layers = nn.Sequential(*layers)
    480 self.norm = norm_layer(self.num_features)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:372, in BasicLayer.__init__(self, dim, input_resolution, depth, num_heads, window_size, mlp_ratio, qkv_bias, drop, attn_drop, drop_path, norm_layer, downsample, use_checkpoint)
    369 self.use_checkpoint = use_checkpoint
    371 # build blocks
--> 372 self.blocks = nn.ModuleList([
    373     SwinTransformerBlock(
    374         dim=dim, input_resolution=input_resolution, num_heads=num_heads, window_size=window_size,
    375         shift_size=0 if (i % 2 == 0) else window_size // 2, mlp_ratio=mlp_ratio,
    376         qkv_bias=qkv_bias, drop=drop, attn_drop=attn_drop,
    377         drop_path=drop_path[i] if isinstance(drop_path, list) else drop_path, norm_layer=norm_layer)
    378     for i in range(depth)])
    380 # patch merging layer
    381 if downsample is not None:
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:373, in <listcomp>(.0)
    369 self.use_checkpoint = use_checkpoint
    371 # build blocks
    372 self.blocks = nn.ModuleList([
--> 373     SwinTransformerBlock(
    374         dim=dim, input_resolution=input_resolution, num_heads=num_heads, window_size=window_size,
    375         shift_size=0 if (i % 2 == 0) else window_size // 2, mlp_ratio=mlp_ratio,
    376         qkv_bias=qkv_bias, drop=drop, attn_drop=attn_drop,
    377         drop_path=drop_path[i] if isinstance(drop_path, list) else drop_path, norm_layer=norm_layer)
    378     for i in range(depth)])
    380 # patch merging layer
    381 if downsample is not None:
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:244, in SwinTransformerBlock.__init__(self, dim, input_resolution, num_heads, window_size, shift_size, mlp_ratio, qkv_bias, drop, attn_drop, drop_path, act_layer, norm_layer)
    241         img_mask[:, h, w, :] = cnt
    242         cnt += 1
--> 244 mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
    245 mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
    246 attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/timm/models/swin_transformer.py:57, in window_partition(x, window_size)
     46 """
     47 Partition into non-overlapping windows with padding if needed.
     48 Args:
   (...)
     54     (Hp, Wp): padded height and width before partition
     55 """
     56 B, H, W, C = x.shape
---> 57 x = x.view(B, H // window_size[0], window_size[0], W // window_size[1], window_size[1], C)
     58 windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size[0], window_size[1], C)
     59 return windows

**Comment by jamesdolezal** [comment] 2024-07-24 18:25
Looking into this today! I can't reproduce the error directly using the provided code, but I'll comb through the error message and see if I can come up with an idea. @Meijian are you also using 2.3.0?

**Comment by Meijian** [comment] 2024-07-24 18:27
Thanks for the quick reply James, I was using SF 2.3.1 and timm 1.0.7.

**Comment by jamesdolezal** [comment] 2024-07-24 18:32
Yes, it's a `timm` version compatibility issue with 1.0. I'll write a fix.

**Comment by Meijian** [comment] 2024-07-24 18:36
Perfect, thank you James!

**Comment by jamesdolezal** [comment] 2024-07-24 18:51
OK - fix is up on `master`. I need to do a more comprehensive test to look for other compatibility issues with `timm` >= 1.0, but this fixes ctranspath.

**Comment by Meijian** [comment] 2024-07-24 18:56
Great! I will try it. 
I have tried other feature extractors like plip, histoSSL, RetCCL, and resnet50, and I haven't encountered any issues.

**Comment by jamesdolezal** [comment] 2024-08-09 18:19
Fixed and released in [2.3.2](https://github.com/jamesdolezal/slideflow/releases/tag/2.3.2)

**Closed by jamesdolezal** 2024-08-09 18:19 UTC
Labels: bug, fixed
